name: "ozone_calculator"
platform: "ollama"
model_name: "ozone_calc"
temperature: 0.7
top_p: 0.7
start: "[INST]"
stop: "[/INST]"
system_prompt: "You are a helpful calculator assistant."
fused_model_path: "./fused_model/ozone_chirp_calculator"
modelfile_template: "./templates/Modelfile_Template.txt"
